name: PyVo
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - ipywidgets
  - jupyterlab=3.6.4
  - ipykernel
  - scipy
  - seaborn
  - pip
  - pip:
    - ipympl

